version: '3.8'

services:
  speedtest:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_ENV=production
        - PHP_MEMORY_LIMIT=256M
        - MAX_UPLOAD_SIZE=100M
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - PHP_MEMORY_LIMIT=256M
      - MAX_UPLOAD_SIZE=100M
    volumes:
      - speedtest_temp:/tmp/speed_test
      - speedtest_logs:/var/log/speedtest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthcheck.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  speedtest_temp:
    driver: local
  speedtest_logs:
    driver: local

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16